### PR TITLE
fix: clean up scan executions and reports after deleting artifact

### LINKED ISSUE #18634: The exec/task/scan report not be cleaned after artifact deleted
The executions, tasks and scan reports of the artifact were not cleaned after deleting the artifacts, it will be the useless data in the database, so should add the cleanup mechanism to recycle these related resources.

### PR DESCRIPTION
**Pull request by chlins**
Cleanup the associated resources(scan executions and scan reports) after deletion of artifact.

Fixes: #18634

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #18634

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

File: src/controller/artifact/controller.go [hunk 1]
```diff
@@ -128,28 +134,43 @@ func NewController() Controller {
 		regCli:       registry.Cli,
 		abstractor:   NewAbstractor(),
 		accessoryMgr: accessory.Mgr,
+		onDeleteFuncs: map[string]OnDeleteFunc{
```
Comment (stonezdj) [inline src/controller/artifact/controller.go:137]: Should we handle these function into the handler of the delete artifact event
https://github.com/goharbor/harbor/blob/d03f0dcf2d6a420e66b486988c3dd00feaeb02d1/src/controller/event/handler/internal/artifact.go#L64 

current implementation seems create unnecessary dependency between artifact and job exection/ scan report

Comment (chlins) [reply src/controller/artifact/controller.go:137]: good point.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by stonezdj — APPROVED** [review]
