### PR TITLE
fix artifact trash filter issue

### LINKED ISSUE #11533: GC doesn't delete the useless manifest and it'sblob
`[Steps]`

1. push hello-world:latest to project A.
2. push hello-world:latest to project B.
3. delete tag of hello-world:latest from project A.
4. run GC with untagged, nothing removed. — artifact projectA/hello-world is removed, but do not call registry API to delete manifest as it’s referenced by project B.
5. delete tag of hello-world:latest from project B.
6. run GC with untagged, GC will call API to remove manifest projectB/hello-world, then do real GC. But, projectA/hello-world still in the back-end storage. GC will not remove any blobs.

`[Root Cause]`
GC is using artifact and artifact trash to decide which manifest should be removed. https://github.com/goharbor/harbor/blob/master/src/jobservice/job/impl/gc/garbage_collection.go#L249 

But, the Trash filter should use repo_name and digest to get the candidate. Currently, it's using digest only.

### PR DESCRIPTION
**Pull request by wy65701436**
fixes #11533

GC jobs will use the filter results to call registry API to delete manifest.

In the current imple, the filter function in some case does not return the deleted artifact as it's using digest as the filter condition.

Like: If one artifact is deleted, but there is another project/repo has a image with same digest with the deleted one, filter func will
not mark the deleted artifact as candidate. It results in, GC job does not call API to remove the manifest.

To fix it, update the filter to use both digest and repository name to filter candidate.

Signed-off-by: wang yan <wangyan@vmware.com>

### CODE REVIEW

File: src/jobservice/job/impl/gc/garbage_collection.go [hunk 1]
```diff
@@ -235,28 +236,32 @@ func (gc *GarbageCollector) deleteCandidates(ctx job.Context) error {
...
 			return err
 		}
+		gc.logger.Info("start to delete untagged artifact.")
 		for _, art := range untagged {
-			gc.logger.Infof("delete the untagged artifact: ProjectID:(%d)-RepositoryName(%s)-MediaType:(%s)-Digest:(%s)",
-				art.ProjectID, art.RepositoryName, art.ManifestMediaType, art.Digest)
 			if err := gc.artCtl.Delete(ctx.SystemContext(), art.ID); err != nil {
 				// the failure ones can be GCed by the next execution
 				gc.logger.Errorf("failed to delete untagged:%d artifact in DB, error, %v", art.ID, err)
 			}
```
Comment (heww) [inline src/jobservice/job/impl/gc/garbage_collection.go:244]: `continue` needed here, otherwise line 245 will be logged.

Comment (wy65701436) [reply src/jobservice/job/impl/gc/garbage_collection.go:244]: fixed.
