### PR TITLE
Fix robot account UI issues

### LINKED ISSUE #13492: Update nodejs base image to a more recent version
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Currently harbor portal images are built against nodejs 10.15.0, as can be seen here I think: 

https://github.com/goharbor/harbor/blob/ca8cb87790c4231ff504adfbbe459a1e13291e53/make/photon/portal/Dockerfile#L3

according to https://nodejs.org/en/about/releases/ nodejs 10.x is in LTS mode, and 10.15 not the latest release (which I think is 10.27.x right now). This is missing a number of bug and security fixes. 

I am wondering what the plan of upgrading is (either newer version that is not in LTS or at least the most recent 10.x release) for harbor 2.1.x. 

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.1]

### PR DESCRIPTION
**Pull request by AllForNothing**
And Fixes #13492
Signed-off-by: AllForNothing <sshijun@vmware.com>

### CODE REVIEW

File: src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.ts [hunk 1]
```diff
@@ -281,6 +284,17 @@ export class NewRobotComponent implements OnInit, OnDestroy {
       return true;
     }
     if (this.coverAll !== this.coverAllForEdit) {
+      if (this.coverAll) {
```
Comment (jwangyangls) [inline src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.ts:287]: The logic can be sorted out and line 300.

Comment (AllForNothing) [reply src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.ts:287]: Fixed

**Review by jwangyangls — APPROVED** [review]
lgtm

**Review by xuelichao — APPROVED** [review]
