### PR TITLE
fix(quota): fix computeResources method of qutoa interceptor

### LINKED ISSUE #8701: artifact count is not updated after deleting a chart
1. Upload a chart a project via UI
2. On project summary page the count increased by 1
3. Delete the chart via UI
4. On project summary page the artifact size remain unchanged.

### PR DESCRIPTION
**Pull request by heww**
Fix #8701

Signed-off-by: He Weiwei <hweiwei@vmware.com>

### CODE REVIEW

File: src/core/middlewares/chart/builder.go [hunk 1]
```diff
@@ -103,20 +103,23 @@ func (*chartVersionCreationBuilder) Build(req *http.Request) (interceptor.Interc
...
-		return nil, fmt.Errorf("failed to parse chart from body, error: %v", err)
-	}
-	chartName, version := chart.Metadata.Name, chart.Metadata.Version
-
-	info := &util.ChartVersionInfo{
-		ProjectID: project.ProjectID,
-		Namespace: namespace,
-		ChartName: chartName,
-		Version:   version,
+	info, ok := util.ChartVersionInfoFromContext(req.Context())
```
Comment (ywk253100) [inline src/core/middlewares/chart/builder.go]: Not quite understand why we need to update the `chartVersionCreationBuilder ` instead of  `chartVersionDeletionBuilder ` as the issue #8701 is caused when deleting a chart

File: src/core/middlewares/interceptor/quota/quota.go [hunk 2]
```diff
@@ -135,7 +135,8 @@ func (qi *quotaInterceptor) computeResources(req *http.Request) error {
 		return nil
 	}
 
-	if len(qi.opts.Resources) == 0 && qi.opts.OnResources != nil {
+	qi.resources = qi.opts.Resources
```
Comment (wy65701436) [inline src/core/middlewares/interceptor/quota/quota.go]: what's the difference?

Comment (wy65701436) [reply src/core/middlewares/interceptor/quota/quota.go]: delete chart is using opt.Resources(types.ResourceList{types.ResourceCount: 1}, but it still cannot satisfy the condition?

Comment (heww) [reply src/core/middlewares/interceptor/quota/quota.go]: quotaInterceptor reserve and unreserve will process the resources saved in quotaInterceptor struct.

This change ensure that resources will first get from the Resources of opts, if it is empty, then try to compute resources.

Comment (wy65701436) [reply src/core/middlewares/interceptor/quota/quota.go]: ok，got it.
