### PR TITLE
Suppress aborthandler

### LINKED ISSUE #18087: Handler crashed with error net/http: abort Handler
**Expected behavior and actual behavior:**
When pulling from a proxy cache project we see panics in `harbor-core`

(sorry the image here is from a private quay repo, used to upgrade an openshift cluster, if you do not have a Red Hat subscription, you won't have access to it but it's the only logs I've right now, the problem also occur with non-proxy cache projects and other public/private images)

```
2023/01/10 10:14:22.658 [1;35m[C][0m [config.go:500]  the request url is  /v2/quay.io_openshift-release-dev/openshift-release-dev/ocp-v4.0-art-dev/blobs/sha256:79a35526965599b4684f26fbce8f776c0bf80e38d28ee31afdc70b6f5c590cc2
2023/01/10 10:14:22.658 [1;35m[C][0m [config.go:501]  Handler crashed with error net/http: abort Handler
2023/01/10 10:14:22.658 [1;35m[C][0m [config.go:507]  /usr/local/go/src/runtime/panic.go:884
2023/01/10 10:14:22.658 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/httputil/reverseproxy.go:363
2023/01/10 10:14:22.658 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/repoproxy/proxy.go:76
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/repoproxy/proxy.go:52
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/metric/metric.go:84
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/v2auth/auth.go:170
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/router/router.go:92
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/vendor/github.com/beego/beego/v2/server/web/router.go:1149
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/vendor/github.com/beego/beego/v2/server/web/filter.go:83
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/vendor/github.com/beego/beego/v2/server/web/router.go:1002
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:52
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/security/security.go:75
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/security/security.go:62
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/artifactinfo/artifact_info.go:96
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.659 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:52
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/notification/notification.go:31
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/orm/orm.go:54
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:52
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/session/session.go:35
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/log/log.go:33
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/requestid/requestid.go:43
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/metric/metric.go:51
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/trace/trace.go:28
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/mergeslash/mergeslash.go:17
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/url/parse.go:22
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2109
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:2947
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/net/http/server.go:1991
2023/01/10 10:14:22.660 [1;35m[C][0m [config.go:507]  /usr/local/go/src/runtime/asm_amd64.s:1594
```

The cluster report back the following error when trying to pull the image from harbor:
```
Failed to pull image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7459b3d89433e97e5d5a73b20f80c68e89a6286d0a71d46053462cc2aef1c378": rpc error: code = Unknown desc = writing blob: storing blob to file "/var/tmp/storage199032593/1": happened during read: unexpected EOF
```

After some retries the image is finally pulled in the cache and operations continue normally.

**Steps to reproduce the problem:**
Difficult to provide as the problem is intermittent; it also seems to happen on non proxy projects (have seen the seem panic on a replicated project but logs are already rotated)

**Versions:**
- harbor version: 2.7.0
- kubernetes version: 1.22
- openshift version: 4.9

### PR DESCRIPTION
**Pull request by ianseyer**
Fixes #18087, #15751, #10813, #12011, #16556, #20148

As per https://github.com/golang/go/issues/28239, it is the expectation that middleware using net/http is responsible for handling http.AbortHandler panics that are automatically recovered.

In the current situation, any network connectivity blip, despite recovering successfully, results in a panic being written to the logs. 

I have tested this build in our staging environment, and the panic message is indeed suppressed. We do see a proxy connection interrupted log message, which is to be expected (we have a reliable source of network connectivity blips).

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by Vad1mo** [comment]
Thank you for your contribution, this is a quite common issue, we have also seen ourself.

File: src/server/middleware/repoproxy/proxy.go [hunk 1]
```diff
@@ -65,6 +65,25 @@ func handleBlob(w http.ResponseWriter, r *http.Request, next http.Handler) error
...
+	// golang/go#28239
+	defer func() {
+		r := recover()
+		err, ok := r.(error)
+
+		switch {
+		case r == nil:
+			return
+
+		case ok && errors.Is(err, http.ErrAbortHandler):
```
Comment (reasonerjt) [inline src/server/middleware/repoproxy/proxy.go:79]: Would be good to print a log with this error, just in case there are very frequent network connection issues.

**Review by reasonerjt — APPROVED** [review]
LGTM

**Review by Vad1mo — APPROVED** [review]

**Review by bupd — APPROVED** [review]
lgtm
