### PR TITLE
fix: fix replication of multiple projects with numeric names

### LINKED ISSUE #19027: When the project name is a number, the replication error
image
image
image

error.log
```
2023-07-26T09:30:00Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: cannot convert 555 to Text"}]} 
```

### PR DESCRIPTION
**Pull request by cgirard-mir**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

The original fix to #19027 contained in #19090 worked well for replicating a single project whose name was numeric, but did not resolve the issue when multiple numeric project names were provided.

The issue was in the construction of the API call. The query parameter was previously being constructed as `name={'123 456 789'}`. With the addition of some debug logging ~(also included in this PR)~, I noticed that the server was parsing this as `'123`, `456`, `789'`. Note that the single quotes were being associated with the first and last values of the list, so these values were forced into parsing as string values. However, the middle value contains only numbers and so was parsed as such. This doesn't cause a problem when only 1 or 2 values are being passed, but can show itself once there are 3 or more values.

The solution is to surround each project name in quotes, `name={'123' '456' '789'}`, so they are all handled as strings by the server.

# Issue being fixed
Further fixes #19027.

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by cgirard-mir** [comment]
FYI, all of the tests were previously passing on this, but after I updated the branch for "out-of-date with base", the test statuses have been reset. Since I don't have permission to run those tests, I'm not planning to do another "Update branch" until they've been re-run and the PR has 2 approvals from maintainers.

**Review by chlins — APPROVED** [review]
lgtm

File: src/lib/q/builder.go [hunk 1]
```diff
@@ -189,19 +189,22 @@ func parseList(value string, c rune) ([]interface{}, error) {
 
 // try to parse value as time first, then integer, and last string
 func parseValue(value string) interface{} {
+	var ret any
 	value = strings.TrimSpace(value)
```
Comment (wy65701436) [inline src/lib/q/builder.go:193]: Thanks @cgirard-mir for the fix, great catch!

Regarding the refactor, I feel the original implementation is more straightforward. If there’s no change in logic, could we keep it as is?

Comment (cgirard-mir) [reply src/lib/q/builder.go:193]: The refactor adds a debug-level logging line to the function (see below). I can remove this commit, though, if you aren't interested in keeping that.

Comment (wy65701436) [reply src/lib/q/builder.go:193]: If you'd like to add the debug log, could you please include it in the original code?

I still prefer to keep the original structure, as it returns early and avoids excessive if-else conditions.

Comment (cgirard-mir) [reply src/lib/q/builder.go:193]: I'll just drop the commit. I don't want to have a logging line in each `if` block.

Comment (cgirard-mir) [reply src/lib/q/builder.go]: The refactoring has been reverted. Only the bug fix commit remains.

**Review by bupd — APPROVED** [review]
lgtm

**Comment by bupd** [comment]
Thanks for your contribution. 
I can confirm this sure is a problem in replication and this PR can be a simple fix for the problem
  
i can confirm

**Review by wy65701436 — APPROVED** [review]
lgtm
