### PR TITLE
fix: cron string validation

### LINKED ISSUE #18091: Validators for Harbor APIs
In order to improve user experience and strengthen security, let's make the validators of the front and back ends consistent:
- [ ] 1:  Post `/api/2.0/projects`,    `storage_limit`  should  range  from -1 to 1024TiB
- [ ] 2: For all cron string,    the first field should always be `0`
- [x] 3: Cron string for replication rule, the second field can not be `*`
- [x] 4: Tag name, see #18073
- [x] 5: Secret length for robot account, should range from 8 to 128
- [x] 6: P2p-preheat policy, `name` should follow the pattern `^[a-z0-9]+(?:[._-][a-z0-9]+)*$`

### PR DESCRIPTION
**Pull request by zyyw**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #18091
task 2

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by AllForNothing — APPROVED** [review]
lgtm

File: src/common/utils/utils.go [hunk 1]
```diff
@@ -301,6 +301,25 @@ func CronParser() cronlib.Parser {
...
+// ValidateCronString check whether it is a valid cron string and whether the 1st field (indicating Seconds of time) of the cron string is a fixed value of 0 or not
+func ValidateCronString(cron string) (bool, error) {
+	if len(cron) == 0 {
+		return false, fmt.Errorf("empty cron string is invalid")
+	}
+	_, err := CronParser().Parse(cron)
+	if err != nil {
+		return false, err
+	}
+	cronParts := strings.Split(cron, " ")
```
Comment (wy65701436) [inline src/common/utils/utils.go:313]: CronParser().Parse should cover this situation, there is no need to check this.

Comment (wy65701436) [inline src/common/utils/utils.go:313]:
```
_, err := CronParser().Parse(cron)
if err != nil {
   return false, err
}

t, ok := s.(*cronlib.SpecSchedule)
if ok {
    if t.Second == 0 {
	    return false, err
    }
}
```

File: src/pkg/p2p/preheat/models/policy/policy.go [hunk 2]
```diff
@@ -118,6 +118,19 @@ type Trigger struct {
 	} `json:"trigger_setting,omitempty"`
 }
 
+// ValidatePreheatPolicy validate preheat policy
+func (s *Schema) ValidatePreheatPolicy() error {
+	// currently only validate cron string of preheat policy
+	if s.Trigger != nil && s.Trigger.Type == TriggerTypeScheduled && len(s.Trigger.Settings.Cron) > 0 {
```
Comment (wy65701436) [inline src/pkg/p2p/preheat/models/policy/policy.go:124]: duplicate validation in the length of cron string

File: src/pkg/p2p/preheat/models/policy/policy.go [hunk 3]
```diff
@@ -118,6 +118,19 @@ type Trigger struct {
...
+		isValid, err := utils.ValidateCronString(s.Trigger.Settings.Cron)
+		if !isValid || err != nil {
```
Comment (wy65701436) [inline src/pkg/p2p/preheat/models/policy/policy.go:126]:
```
if err != nil {
 return err --- this is 500 error
}
if !isValid {
 return BadRequest -- this is 400 error
}
```

File: src/pkg/retention/policy/models.go [hunk 4]
```diff
@@ -58,6 +60,24 @@ type Metadata struct {
 	Scope *Scope `json:"scope" valid:"Required"`
 }
 
+// ValidateRetentionPolicy validate the retention policy
+func (m *Metadata) ValidateRetentionPolicy() error {
```
Comment (wy65701436) [inline src/pkg/retention/policy/models.go:64]: ditto

File: src/pkg/p2p/preheat/models/policy/policy.go (hunk 2 above)
Comment (zyyw) [reply src/pkg/p2p/preheat/models/policy/policy.go:124]: This is because we need to skip `utils.ValidateCronString()` validation for cron with empty string "". In preheat and tag retention, it uses empty string cron to unschedule an existing job.

File: src/pkg/retention/policy/models.go (hunk 4 above)
Comment (zyyw) [reply src/pkg/retention/policy/models.go:64]: Same as above. This is because we need to skip `utils.ValidateCronString()` validation for cron with empty string "". In preheat and tag retention, it uses empty string cron to unschedule an existing job.

File: src/pkg/p2p/preheat/models/policy/policy.go (hunk 3 above)
Comment (zyyw) [reply src/pkg/p2p/preheat/models/policy/policy.go:126]: actually，when the first field of cron is not 0, like "1 0 0 1 1 *", `utils.ValidateCronString` will return `false` and with error message. This is a BadRequest.

Comment (zyyw) [reply src/pkg/p2p/preheat/models/policy/policy.go:126]: maybe for `utils.ValidateCronString()` we should only return `error`, instead of return `(bool, error)`

**Review by stonezdj — APPROVED** [review]
