### PR TITLE
Call /v2/auth/token api to get bearer token for dockerhub adapter

### LINKED ISSUE #23025: Proxy Cache project not working on v2.15.0
**Expected behavior and actual behavior:**
Project with Proxy Cache type not working with `v2.15.0` with message below
```
Error response from daemon: unknown: artifact mirror/portainer/portainer-ce:lts not found
```

**Steps to reproduce the problem:**
try to  docker pull any image from the proxy cache project and message above pops up

I tried to downgrade to `v2.14.3` and the proxy cache project works again

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.15.0]
- docker engine version: [29.3.0]
- docker-compose version: [5.1.1]

### PR DESCRIPTION
**Pull request by stonezdj**
fixes #23025 
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by stonezdj** [comment]
Verified in my local dev env, monitored the health status for dockerhub registry for 1 weeks or so, no unhealthy status found with this new API. 
Dockerhub support also confirmed that the new API (v2/auth/token) is more stable than the previous one.

API document: https://docs.docker.com/reference/api/hub/latest/#tag/authentication-api/operation/AuthCreateAccessToken

File: src/pkg/reg/adapter/dockerhub/client.go [hunk 1]
```diff
@@ -94,17 +100,38 @@ func (c *Client) refreshToken() error {
...
 	token := &TokenResp{}
-	err = json.Unmarshal(body, token)
-	if err != nil {
+	if err = json.Unmarshal(body, token); err != nil {
 		return fmt.Errorf("unmarshal token response error: %v", err)
 	}
 
-	c.token = token.Token
+	c.token = token.AccessToken
+	// Tokens issued by /v2/auth/token expire after 10 minutes; refresh 1 minute
```
Comment (chlins) [inline src/pkg/reg/adapter/dockerhub/client.go:108]: Is the 10 minutes fixed by DockerHub in it's API docs or just an experience value?

File: src/pkg/reg/adapter/dockerhub/client.go [hunk 2]
```diff
@@ -94,17 +100,38 @@ func (c *Client) refreshToken() error {
...
+	// early to avoid using a token that is about to expire.
+	c.tokenExpiry = time.Now().Add(9 * time.Minute)
```
Comment (chlins) [inline src/pkg/reg/adapter/dockerhub/client.go:110]: Is 1 minute enough to cover the subsequent requests?

File: src/pkg/reg/adapter/dockerhub/client.go (hunk 1 above)
Comment (stonezdj) [reply src/pkg/reg/adapter/dockerhub/client.go:108]: Fixed value. see doc: https://docs.docker.com/reference/api/hub/latest/#tag/authentication-api/operation/AuthCreateAccessToken

File: src/pkg/reg/adapter/dockerhub/client.go (hunk 2 above)
Comment (stonezdj) [reply src/pkg/reg/adapter/dockerhub/client.go:110]: Sure, ensureToken is invoked before HTTP request to dockerhub, so 1 minute is enough.

**Review by chlins — APPROVED** [review]
lgtm

**Review by wy65701436 — APPROVED** [review]
lgtm
