### PR TITLE
fix(core): add warning when config admin password is ignored

### LINKED ISSUE #22704: change config harbor_admin_password params, start harbor service occur "username or password is not correct"
if not change password, it correct start, but i want when initialization change password,
and i uncomment https params, maybe is affect?
```
# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 80

# https related config
#https:
  # https port for harbor, default is 443
  #port: 443
  # The path of cert and key files for nginx
  #certificate: /your/certificate/path
  #private_key: /your/private/key/path
  # enable strong ssl ciphers (default: false)
  # strong_ssl_ciphers: false
```

### PR DESCRIPTION
**Pull request by thc1006**
## Summary

- Add warning log when `harbor_admin_password` in config is ignored because admin password already exists in database
- Refactor `updateInitPassword` for testability with dependency injection
- Add unit tests for password initialization scenarios

## Background

The `harbor_admin_password` setting only applies during initial installation. When users modify this value after Harbor is running, the change is silently ignored, leading to "username or password is not correct" errors when they try to login with the new password.

This is documented behavior but causes recurring confusion (see related issues below).

## Changes

**src/core/main.go**
- Extract `updateInitPasswordWithMgr` to accept user manager as parameter
- Add warning log when config password is set but will not be applied

**src/core/main_test.go** (new)
- Test: new user password initialization
- Test: existing user password skip
- Test: warning when config password set
- Test: no warning when config password empty

## Test Plan

- [x] Unit tests pass locally
- [x] Build passes
- [ ] Manual verification with Harbor deployment

## Related Issues

Fixes #22704

Related: #21981, #17122, #12639, #11600

### CODE REVIEW

**Comment by thc1006** [comment]
**TL;DR:** Kindly requesting a re-run of the failed `APITEST_DB_PROXY_CACHE` job and the addition of a `release-note/fix` label. Both failures appear unrelated to the code changes in this PR.

---

Dear maintainers,

Thank you very much for taking the time to review this pull request. I have carefully analyzed the CI failures and would like to respectfully share my findings.

**Regarding `APITEST_DB_PROXY_CACHE` failure:**

The test failure shows `Test Case - Proxy Cache | FAIL | 1 != 0`, which appears to be a flaky test or infrastructure-related issue. This PR only modifies the admin password warning logic in `src/core/main.go` and its corresponding unit tests, and does not touch any Proxy Cache functionality. I have observed that other recent PRs have also experienced similar intermittent failures with this particular test.

I would be most grateful if you could kindly re-run the failed job at your convenience.

**Regarding `Check release-note label set` failure:**

This PR requires a `release-note/*` label to pass the CI check. Since this is a bug fix that addresses issue #22704, I believe `release-note/fix` would be the appropriate label.

Would you be so kind as to add this label when you have a moment?

I sincerely apologize for any inconvenience this request may cause. Please do not hesitate to let me know if there is anything I should modify or if you have any concerns about the implementation.

Thank you very much for your time and consideration.

Best regards

File: src/core/main.go [hunk 1]
```diff
@@ -87,7 +87,10 @@ const (
 )
 
 func updateInitPassword(ctx context.Context, userID int, password string) error {
-	userMgr := pkguser.Mgr
+	return updateInitPasswordWithMgr(ctx, pkguser.Mgr, userID, password)
```
Comment (wy65701436) [inline src/core/main.go:91]: do we need the updateInitPasswordWithMgr here? why not update the updateInitPassword directly?

File: src/core/main.go [hunk 2]
```diff
@@ -97,10 +100,13 @@ func updateInitPassword(ctx context.Context, userID int, password string) error
 		if err != nil {
 			return fmt.Errorf("failed to update user encrypted password, userID: %d, err: %v", userID, err)
 		}
-
 		log.Infof("User id: %d updated its encrypted password successfully.", userID)
 	} else {
 		log.Infof("User id: %d already has its encrypted password.", userID)
+		if password != "" {
+			log.Warningf("The admin password in configuration (HARBOR_ADMIN_PASSWORD) will not be applied " +
```
Comment (wy65701436) [inline src/core/main.go]: How can we determine whether the user is a Harbor admin? At the very least, should we check the user ID?

File: src/core/main.go [hunk 3]
```diff
@@ -97,10 +97,13 @@ func updateInitPassword(ctx context.Context, userID int, password string) error
 		if err != nil {
 			return fmt.Errorf("failed to update user encrypted password, userID: %d, err: %v", userID, err)
 		}
-
 		log.Infof("User id: %d updated its encrypted password successfully.", userID)
 	} else {
 		log.Infof("User id: %d already has its encrypted password.", userID)
+		if userID == adminUserID && password != "" {
```
Comment (chlins) [inline src/core/main.go:107]: Please simplify to use `Warning` because no format needed and the log message can be use one sentence to avoid `+` cost.

Comment (thc1006) [reply src/core/main.go:107]: Dear @chlins ,
Done. Changed to log.Warning and combined the message into a single line.
