### PR TITLE
append pull permission for push policy

### LINKED ISSUE #11225: [Robot Account] Can't push image to a prviate project
POST api/v2.0/projects/1/robots

If this API with payload as below, push image to a private project is success:

    {"name":"ddd","expires_at":-1,"access":[{"resource":"/project/1/repository","action":"push"},{"resource":"/project/1/repository","action":"pull"}]}

image

If this API with payload as below, push image to a private project is fail:

    {"name":"uuu","expires_at":-1,"access":[{"resource":"/project/1/repository","action":"push"}]}

image

**Harbor Version : v2.0.0-4187b375**

### PR DESCRIPTION
**Pull request by wy65701436**
Fixes #11225
As registry changes to basic auth, the push action lost the pull permission.
Add it in the robot security context.

Signed-off-by: wang yan <wangyan@vmware.com>

### CODE REVIEW

File: src/common/security/robot/robot.go [hunk 1]
```diff
@@ -40,8 +41,12 @@ func filterPolicies(namespace types.Namespace, policies []*types.Policy) []*type
 	for _, policy := range policies {
 		if types.ResourceAllowedInNamespace(policy.Resource, namespace) {
 			results = append(results, policy)
+			// give the PUSH action a pull access
+			if policy.Action == rbac.ActionPush {
+				pull := &types.Policy{Resource: namespace.Resource(rbac.ResourceRepository), Action: rbac.ActionPull}
```
Comment (heww) [inline src/common/security/robot/robot.go]: Copy from the policy and modify its action to `rbac.ActionPull`

Comment (wy65701436) [reply src/common/security/robot/robot.go]: gotcha, updated.
