### PR TITLE
Fix #8319, got error when replicating image with Azure container registry

### LINKED ISSUE #8319: Pull-based replication error for Azure ACR
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

```
2019-07-17T13:38:38Z [INFO] [/replication/transfer/image/transfer.go:95]: client for source registry [type: azure-acr, URL: https://harbor.azurecr.io, insecure: false] created
2019-07-17T13:38:38Z [INFO] [/replication/transfer/image/transfer.go:105]: client for destination registry [type: harbor, URL: http://core:8080, insecure: true] created
2019-07-17T13:38:38Z [INFO] [/replication/transfer/image/transfer.go:138]: copying dev/busybox:[1.30.0](source registry) to develop/busybox:[1.30.0](destination registry)...
2019-07-17T13:38:38Z [INFO] [/replication/transfer/image/transfer.go:157]: copying dev/busybox:1.30.0(source registry) to develop/busybox:1.30.0(destination registry)...
2019-07-17T13:38:38Z [INFO] [/replication/transfer/image/transfer.go:261]: pulling the manifest of image dev/busybox:1.30.0 ...
2019-07-17T13:38:38Z [INFO] [/replication/transfer/image/transfer.go:272]: the manifest of image dev/busybox:1.30.0 pulled
2019-07-17T13:38:38Z [INFO] [/replication/transfer/image/transfer.go:231]: copying the blob sha256:3a093384ac306cbac30b67f1585e12b30ab1a899374dabc3170b9bca246f1444...
2019-07-17T13:47:02Z [ERROR] [/replication/transfer/image/transfer.go:244]: failed to pulling the blob sha256:3a093384ac306cbac30b67f1585e12b30ab1a899374dabc3170b9bca246f1444: http error: code 400, message 锘�<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.
RequestId:bd529764-401e-00f6-3fa5-3c01a4000000
Time:2019-07-17T13:46:00.6942963Z</Message></Error>
2019-07-17T13:47:02Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 400, message 锘�<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.
RequestId:bd529764-401e-00f6-3fa5-3c01a4000000
Time:2019-07-17T13:46:00.6942963Z</Message></Error>
```

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

### PR DESCRIPTION
**Pull request by ywk253100**
Fix #8319, got error when replicating image with Azure container registry

Signed-off-by: Wenkai Yin <yinw@vmware.com>

### CODE REVIEW

File: src/common/utils/registry/auth/tokenauthorizer.go [hunk 1]
```diff
@@ -111,7 +111,13 @@ func (t *tokenAuthorizer) Modify(req *http.Request) error {
...
-	req.Header.Add(http.CanonicalHeaderKey("Authorization"), fmt.Sprintf("Bearer %s", token.Token))
+	tokenContent := token.Token
+	// the token returned by azure container registry is called "access_token"
+	if len(tokenContent) == 0 {
+		tokenContent = token.AccessToken
+	}
+
+	req.Header.Add(http.CanonicalHeaderKey("Authorization"), fmt.Sprintf("Bearer %s", tokenContent))
 
 	return nil
```
Comment (steven-zou) [inline src/common/utils/registry/auth/tokenauthorizer.go]: Can we check the empty of token and return the corresponding error？
