### PR TITLE
fix(api): escape path paramters before APIs and unescape them in the Prepare of operations

### LINKED ISSUE #10860: The path parameter defined in swagger cannot contain slash
The API call fails if the repository name contains slash:
```
yinw-a01:cnab-to-oci yinw$ curl -i -u admin:Harbor12345 http://127.0.0.1/api/v2.0/projects/library/repositories/demo/hello-world
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 27 Feb 2020 00:52:28 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 122
Connection: keep-alive
Set-Cookie: sid=293b5f3f56e1ebac7ec7568bd765edab; Path=/; HttpOnly
X-Request-Id: 4c11709d-c6d3-4931-87fa-83692b39248a

{"errors":[{"code":"NOT_FOUND","message":"path /api/v2.0/projects/library/repositories/demo/hello-world was not found"}]}
```

### PR DESCRIPTION
**Pull request by heww**
fix(api): escape path paramters before APIs and unescape them in the Prepare of operations

1. Escape the path paramters before the APIs.
2. Unescape the path paramters in the Prepare stage of the swagger
operations.

Closes #10860

Signed-off-by: He Weiwei <hweiwei@vmware.com>

### CODE REVIEW

File: src/server/middleware/path/path.go [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+	"net/http"
+	"net/url"
+	"regexp"
+
+	"github.com/goharbor/harbor/src/server/middleware"
+)
+
+var (
+	defaultRegexps = []*regexp.Regexp{
+		regexp.MustCompile(`^/api/v2.0/projects/.*/repositories/(.*)/artifacts/?$`),
```
Comment (ywk253100) [inline src/server/middleware/path/path.go]: How about replace the `2.0` with regexp as the version will bump up and we main maintain multiple versions of API
