### PR TITLE
fix: escape the event data for slack webhook payload

### LINKED ISSUE #18423: Slack cannot receive TAG_RETENTION webhook
How can we help you?

As the invalid payload of tag retention, so currently the slack cannot receive the webhook notification successfully from harbor.

```
2023-03-25T08:59:27Z [INFO] [/jobservice/job/impl/notification/slack_job.go:81]: start to run slack job
2023-03-25T08:59:27Z [INFO] [/jobservice/job/impl/notification/slack_job.go:120]: send request to remote endpoint, body: {
	"blocks": [
		{
            "type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*Harbor webhook events*"
			}
        },
        {
            "type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*event_type:* TAG_RETENTION"
			}
        },
        {
            "type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*occur_at:* <!date^1679734643^{date} at {time}|February 18th, 2014 at 6:39 AM PST>"
			}
        },
        {	"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*operator:* MANUAL"
			}
		},
        {	"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*event_data:*"
			}
		},
		{	"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "```{
	\"retention\": {
		\"total\": 1,
		\"retained\": 0,
		\"harbor_hostname\": \"localhost\",
		\"project_name\": \"library\",
		\"retention_policy_id\": 1,
		\"retention_rule\": [
			{
				\"template\": \"always\",
				\"tag_selectors\": [
					{
						\"kind\": \"doublestar\",
						\"decoration\": \"matches\",
						\"pattern\": \"11\",
						\"extras\": \"{\\"untagged\\":true}\"
					}
				],
				\"scope_selectors\": {
					\"repository\": [
						{
							\"kind\": \"doublestar\",
							\"decoration\": \"repoMatches\",
							\"pattern\": \"busybox\",
							\"extras\": \"\"
						}
					]
				}
			}
		],
		\"result\": \"SUCCESS\",
		\"deleted_artifact\": [
			{
				\"type\": \"image\",
				\"status\": \"SUCCESS\",
				\"name_tag\": \"busybox:latest\"
			}
		]
	}
}```"
			}
		}
    ]}
2023-03-25T08:59:27Z [ERROR] [/jobservice/job/impl/notification/slack_job.go:85]: exit slack job, error: abnormal response code: 400, body: invalid_payload
```

### PR DESCRIPTION
**Pull request by chlins**
Escape the event data of slack webhook as original payload is invalid when send to slack.

Fixes: #18423

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #18423

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

File: src/pkg/notifier/handler/notification/slack_handler_test.go [hunk 1]
```diff
@@ -105,3 +104,32 @@ func TestSlackHandler_Name(t *testing.T) {
...
+		{
+			name: `escape "`,
+			args: args{str: `{"foo":"bar"}`},
+			want: `{\"foo\":\"bar\"}`,
+		},
+		{
+			name: `escape \\"`,
+			args: args{str: `{\"foo\":\"bar\"}`},
+			want: `{\\\"foo\\\":\\\"bar\\\"}`,
+		},
```
Comment (zyyw) [inline src/pkg/notifier/handler/notification/slack_handler_test.go:126]: according to the `args` & `want`, it seems that the code is escaping `\"`, instead of `\\"`. Could you please elaborate it? Thanks

Comment (chlins) [reply src/pkg/notifier/handler/notification/slack_handler_test.go:126]: If the input is `{\"foo\":\"bar\"}`, then `escapeEventData` function will firstly escape the symbol `"`, so the input now will look like `{\\"foo\\":\\"bar\\"}`, but it's not valid because `\` also need to be escaped, so 
 `escapeEventData` function again convert `\\"` => `\\\"` to escape the `\`.

Comment (zyyw) [reply src/pkg/notifier/handler/notification/slack_handler_test.go:126]: sorry, it seems that I understand it now. `{\"foo\":\"bar\"}` is replaced to `{\\"foo\\":\\"bar\\"}` first by ```
	// escape " to \"
	str = strings.Replace(str, `"`, `\"`, -1)
```
and then replaced to `{\\\"foo\\\":\\\"bar\\\"}` by 
```
	// escape \\" to \\\"
	str = strings.Replace(str, `\\"`, `\\\"`, -1)
```

**Review by zyyw — APPROVED** [review]

**Review by wy65701436 — APPROVED** [review]
lgtm
