### PR TITLE
fix[jobservice]:job status is hung after restart

### LINKED ISSUE #9963: Scan all status is hung after migration from 1.8 to 1.10
Test Steps:
    1. Deploy harbor 1.8.5;
    2. Set Scan all shedule to 12 12 12 * * *;
    3. Wait more than 12 minutes;
    4. Update harbor to 1.10;
    5. View page of "Interrogation Services";
Result:
    Page is in scan waiting status for long time.

### LINKED ISSUE #10244: restart of Redis server will cause the restart of jobservice
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Restart Redis, the jobservice will be restarted. actually it should not.

**Steps to reproduce the problem:**

Restart the Redis server

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
None.

### PR DESCRIPTION
**Pull request by steven-zou**
- improve the status hook sending/resending approach
- improve the status compare and set approach
- simplify the relevant flow
- add reaper to fix the out of sync jobs
- fix #10244 , fix #9963

Signed-off-by: Steven Zou <szou@vmware.com>

### CODE REVIEW

File: src/jobservice/hook/hook_agent.go [hunk 1]
```diff
@@ -95,47 +85,53 @@ type basicAgent struct {
...
+		}
+
+		logger.Warningf("Send hook event '%s' to '%s' failed with error: %s; push hook event to the queue for retrying later", evt.Message, evt.URL, err)
+		// Treat as successful hook event as the event has been put into the retry queue for future resending.
+		return nil
+	}
+
+	// Mark event hook ACK including "revision", "status" and "check_in_at" in the job stats to indicate
+	// the related hook event has been successfully fired.
+	// The ACK can be used by the reaper to justify if the hook event should be resent again.
```
Comment (stonezdj) [inline src/jobservice/hook/hook_agent.go]: Repair?

**Comment by steven-zou** [comment]
job_status

**Comment by steven-zou** [comment]
job_flow
