### PR TITLE
Skip scan in-toto sbom artifact

### LINKED ISSUE #20337: Got crash on scan all
Apr 23 09:12:34 yminer core[71669]: 2024-04-23T09:12:34Z [INFO] [/server/middleware/security/robot.go:71][requestID="d43d4e35-5164-4700-89bf-e5ab6cd70123"]: a robot security context generated for request GET /service/token
Apr 23 09:12:35 yminer core[71669]: 2024-04-23T09:12:35Z [INFO] [/server/middleware/security/robot.go:71][requestID="df833b9f-08b6-4809-bb47-a5f3799dfb41"]: a robot security context generated for request GET /service/token
Apr 23 09:12:35 yminer core[71669]: 2024-04-23T09:12:35Z [INFO] [/server/middleware/security/robot.go:71][requestID="91923797-932d-4beb-a227-2c45b31dfc53"]: a robot security context generated for request GET /service/token
Apr 23 09:12:36 yminer core[71669]: 2024-04-23T09:12:36Z [INFO] [/server/middleware/security/robot.go:71][requestID="072c8ebf-b00e-4dde-bc36-3a1a2b1a62cb"]: a robot security context generated for request GET /service/token
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.764 #033[1;35m[C]#033[0m [config.go:500]  the request url is  /v2/redis/haproxy/blobs/sha256:d657b2c45a2a18e994720e27b522a3a0e41d225ebc3c7e1c12e6cd06b3d60679
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.764 #033[1;35m[C]#033[0m [config.go:501]  Handler crashed with error net/http: abort Handler
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.764 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/runtime/panic.go:770
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.764 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/httputil/reverseproxy.go:516
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/repoproxy/proxy.go:79
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/repoproxy/proxy.go:55
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/metric/metric.go:91
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/v2auth/auth.go:170
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.765 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/router/router.go:92
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /go/pkg/mod/github.com/beego/beego/v2@v2.0.6/server/web/router.go:1149
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /go/pkg/mod/github.com/beego/beego/v2@v2.0.6/server/web/filter.go:83
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /go/pkg/mod/github.com/beego/beego/v2@v2.0.6/server/web/router.go:1002
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:52
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/security/security.go:75
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.766 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.767 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.767 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/security/security.go:62
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.767 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.767 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.767 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/artifactinfo/artifact_info.go:97
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.767 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:52
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/notification/notification.go:31
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/orm/orm.go:54
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.768 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.769 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:52
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.769 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.769 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/session/session.go:35
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.769 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.769 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/log/log.go:43
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.769 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.770 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.770 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/requestid/requestid.go:46
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.770 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.770 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.770 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/metric/metric.go:74
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.770 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.771 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/trace/trace.go:28
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.771 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.771 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/mergeslash/mergeslash.go:31
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.771 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.771 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.771 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/url/parse.go:36
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.771 #033[1;35m[C]#033[0m [config.go:507]  /harbor/src/server/middleware/middleware.go:57
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.772 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2166
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.772 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:3137
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.772 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/net/http/server.go:2039
Apr 23 09:12:36 yminer core[71669]: 2024/04/23 09:12:36.772 #033[1;35m[C]#033[0m [config.go:507]  /usr/local/go/src/runtime/asm_amd64.s:1695

### PR DESCRIPTION
**Pull request by stonezdj**
fixes #20337 
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

File: src/controller/artifact/controller.go [hunk 1]
```diff
@@ -759,3 +763,20 @@ func (c *controller) populateAccessories(ctx context.Context, art *Artifact) {
...
+func (c *controller) HasUnscannableLayer(ctx context.Context, dgst string) (bool, error) {
+	if len(dgst) == 0 {
+		return false, nil
+	}
+	blobs, err := c.blobMgr.GetByArt(ctx, dgst)
+	if err != nil {
+		return false, err
+	}
+	for _, b := range blobs {
+		if b.ContentType == inTotoContentType {
```
Comment (chlins) [inline src/controller/artifact/controller.go:777]: This time we encountered in-toto and skipping it, next time if we encounter other unsupported types, will there be the same problem?

File: src/controller/artifact/controller.go [hunk 2]
```diff
@@ -56,6 +56,8 @@ import (
 	model_tag "github.com/goharbor/harbor/src/pkg/tag/model/tag"
 )
 
+const inTotoContentType = "application/vnd.in-toto+json"
```
Comment (wy65701436) [inline src/controller/artifact/controller.go:59]: can we define an array at least? So then next time, we could just modify data.

File: src/controller/scan/base_controller.go [hunk 3]
```diff
@@ -199,6 +196,17 @@ func (bc *basicController) collectScanningArtifacts(ctx context.Context, r *scan
 			return nil
 		}
 
+		// because there are lots of in-toto sbom artifacts in dockerhub and replicated to Harbor, they are considered as image type
+		// when scanning these type of sbom artifact, they cause many pannic in the harbor-core log
+		// to avoid pannic, skip scan the in-toto sbom artifact sbom artifact
```
Comment (wy65701436) [inline src/controller/scan/base_controller.go:201]: please add more background in terms of panic.

File: src/controller/artifact/controller.go (hunk 1 above)
Comment (wy65701436) [inline src/controller/artifact/controller.go:777]: please give an debug log to tell this artifact is skipped by some reason.

File: src/controller/artifact/controller.go (hunk 2 above)
Comment (stonezdj) [reply src/controller/artifact/controller.go]: Updated

File: src/controller/artifact/controller.go (hunk 1 above)
Comment (stonezdj) [reply src/controller/artifact/controller.go]: The intent of this fix is to avoid panic,  if other type doesn't cause panic, no need to add it in the unsupported list.

**Review by wy65701436 — APPROVED** [review]
lgtm
