### PR TITLE
fix(rbac): NewProjectNamespace in rbac only accept projectID

### LINKED ISSUE #8635: v1.8.2-rc1版本中项目名为数字，该项目的成员无法获得项目中镜像信息，只有harbor管理员可以看到镜像
问题复现：
1.以harbor管理员的帐号登录，创建一个测试项目，项目名为123（整型数即可）。
2.以harbor管理员的帐号推送一个测试镜像，并且添加一个成员给这个项目，角色为项目管理员。
3.切换为添加的这个帐号，查看项目下的镜像，发现无法查看。
代码版本：* （头指针分离于 v1.8.2-rc1） ddc119a15 Merge pull request #8342 from wy65701436/release-1.8.0
通过日志和源码发现：
common/security/local/context.go:109 报错，没有找到project，通过查看Get函数，core/promgr/pmsdriver/local/local.go:41，定位utils.ParseProjectIDOrName(projectIDOrName)函数，common/utils/utils.go:154,这部分代码对非harbor管理员时查找project的逻辑是否有问题？如果传入的参数是一个name为整型的参数是否会导致我目前遇到的问题？
请各位给出宝贵的意见，或者我的代码定位是否有误，请指出，期待各位的帮助，谢谢

### PR DESCRIPTION
**Pull request by heww**
Closes #8635

Signed-off-by: He Weiwei <hweiwei@vmware.com>

### CODE REVIEW

File: src/common/rbac/namespace.go [hunk 1]
```diff
@@ -31,31 +31,31 @@ type Namespace interface {
...
 }
 
 func (ns *projectNamespace) Resource(subresources ...Resource) Resource {
-	return Resource(fmt.Sprintf("/project/%v", ns.projectIDOrName)).Subresource(subresources...)
+	return Resource(fmt.Sprintf("/project/%d", ns.projectID)).Subresource(subresources...)
 }
 
 func (ns *projectNamespace) Identity() interface{} {
-	return ns.projectIDOrName
+	return ns.projectID
```
Comment (ywk253100) [inline src/common/rbac/namespace.go]: The function should return int64 rather than interface{}?

Comment (heww) [reply src/common/rbac/namespace.go]: Because the `Identity` of  `Namespace` interface returns `interface{}`.
