### PR TITLE
fix #8815 :add remove untagged blob record in table project_blob

### LINKED ISSUE #8815: Quota doesn't work as expected after running GC
The steps to reproduce the issue:
1. Prepare a totally fresh Harbor instance without any data
2. Create a project called `yinw` and set storage quota to `200M`
3. Push `golang:1.11.2`(280M) to `yinw`, failed and 160M blobs are pushed, the usage is changed to 160M
4. Run GC, the usage is changed to 0
5. Push again, success and the usage is changed to 120M

### PR DESCRIPTION
**Pull request by wy65701436**
Signed-off-by: wang yan <wangyan@vmware.com>

### CODE REVIEW

File: src/common/dao/project_blob.go [hunk 1]
```diff
@@ -134,3 +134,45 @@ WHERE af.project_id = ?
...
+	var pbIDs []interface{}
+	for _, pb := range projectBlobs {
+		pbIDs = append(pbIDs, pb.ID)
+	}
+
+	if len(pbIDs) == 0 {
+		return nil
+	}
+
+	sql = fmt.Sprintf(`DELETE FROM project_blob WHERE id IN (%s)`, ParamPlaceholderForIn(len(pbIDs)))
```
Comment (ywk253100) [inline src/common/dao/project_blob.go]: The two sql can be merged into one

Comment (wy65701436) [reply src/common/dao/project_blob.go]: as the pq will raise an exception when the IN or NOT IN condition array is empty.
