### PR TITLE
fix(database): generate db url by url.URL for schema upgrade

### LINKED ISSUE #7948: Encode database passwords in harbor's core
**Expected behavior and actual behavior:**
Expected behavior: harbor-core pod running.
Actual behavior: Crashloop backoff on harbor-core pod.

This issue relates to https://github.com/goharbor/harbor-helm/issues/214

A fix has been made on the helm chart regarding db passwords encoding as they may contain special characters and so on.

IMHO Fixing this issue in the helm chart is not enough, or may not be the right place.

**Steps to reproduce the problem:**
This was our db password: `@=?x6BDB32c4tuV%6?8E6g9mj3dkh6%b` and we had the following error in harbor core container:
```
$ kubectl logs harbor-devl-harbor-core-58bcb588b8-jxkkc -c core
2019-05-31T10:11:03Z [INFO] [/replication/adapter/harbor/adapter.go:41]: the factory for adapter harbor registered
2019-05-31T10:11:03Z [INFO] [/replication/adapter/dockerhub/adapter.go:24]: Factory for adapter docker-hub registered
2019-05-31T10:11:03Z [INFO] [/replication/adapter/native/adapter.go:30]: the factory for adapter docker-registry registered
2019-05-31T10:11:03Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:25]: the factory of Huawei adapter was registered
2019-05-31T10:11:03Z [DEBUG] [/core/auth/authenticator.go:126]: Registered authentication helper for auth mode: http_auth
2019-05-31T10:11:03Z [DEBUG] [/core/auth/authenticator.go:126]: Registered authentication helper for auth mode: db_auth
2019-05-31T10:11:03Z [DEBUG] [/core/auth/authenticator.go:126]: Registered authentication helper for auth mode: ldap_auth
2019-05-31T10:11:03Z [DEBUG] [/core/auth/authenticator.go:126]: Registered authentication helper for auth mode: uaa_auth
2019-05-31T10:11:03Z [INFO] [/core/controllers/base.go:288]: Config path: /etc/core/app.conf
2019-05-31T10:11:03Z [INFO] [/core/main.go:92]: initializing configurations...
2019-05-31T10:11:03Z [INFO] [/core/config/config.go:98]: key path: /etc/core/key
2019-05-31T10:11:03Z [INFO] [/core/config/config.go:71]: init secret store
2019-05-31T10:11:03Z [INFO] [/core/config/config.go:74]: init project manager based on deploy mode
2019-05-31T10:11:03Z [INFO] [/core/config/config.go:143]: initializing the project manager based on local database...
2019-05-31T10:11:03Z [INFO] [/core/main.go:96]: configurations initialization completed
2019-05-31T10:11:03Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-localhost port-5432 databse-registry sslmode-"disable"
2019-05-31T10:11:03Z [INFO] [/common/dao/base.go:89]: Register database completed
2019-05-31T10:11:03Z [FATAL] [/core/main.go:103]: failed to initialize database: dial tcp: lookup =: no such host
```
Our guess is that, this is due to the `@` or maybe another character, which misconfigured the db host setting.

Took us a while to find out that our password was the culprit here :smile: 

Note: harbor's core container was the only one failing, the notary server or other components in harbor's ecosystem appeared to be working fine with this password.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.0]
- helm chart version: [v1.1.0]

Do not hesitate to ask any further question,

Thank you for your help!

### PR DESCRIPTION
**Pull request by heww**
Closes #7948

Signed-off-by: He Weiwei <hweiwei@vmware.com>

### CODE REVIEW

File: src/common/dao/pgsql.go [hunk 1]
```diff
@@ -91,14 +92,21 @@ func (p *pgsql) Register(alias ...string) error {
 
 // UpgradeSchema calls migrate tool to upgrade schema to the latest based on the SQL scripts.
 func (p *pgsql) UpgradeSchema() error {
-	dbURL := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=%s", p.usr, p.pwd, p.host, p.port, p.database, p.sslmode)
+	dbURL := url.URL{
+		Scheme:   "postgres",
+		User:     url.UserPassword(p.usr, p.pwd),
+		Host:     p.host,
```
Comment (ninjadq) [inline src/common/dao/pgsql.go]: it seems lost `p.port` part here

Comment (heww) [reply src/common/dao/pgsql.go]: fixed
