### PR TITLE
fix(chart,quota): fix path regexp of chart creation and deletion

### LINKED ISSUE #8806: Chart count is not calculated into the count quota of project
Screen Shot 2019-08-23 at 15 00 57

`1+3 = 4 <> 1`

### PR DESCRIPTION
**Pull request by heww**
Closes #8806 #8701

Signed-off-by: He Weiwei <hweiwei@vmware.com>

### CODE REVIEW

File: src/core/middlewares/chart/builder.go [hunk 1]
```diff
@@ -29,8 +29,8 @@ import (
 )
 
 var (
-	deleteChartVersionRe = regexp.MustCompile(`^/api/chartrepo/(?P<namespace>\w+)/charts/(?P<name>\w+)/(?P<version>[\w\d\.]+)/?$`)
-	createChartVersionRe = regexp.MustCompile(`^/api/chartrepo/(?P<namespace>\w+)/charts/?$`)
+	deleteChartVersionRe = regexp.MustCompile(`^/api/chartrepo/(?P<namespace>[^?#]+)/charts/(?P<name>[^?#]+)/(?P<version>[^?#]+)/?$`)
```
Comment (wy65701436) [inline src/core/middlewares/chart/builder.go]: can it support "123/123/123.tgz"? actually, I can give any name for the tgz when to load the chat file.

Comment (heww) [reply src/core/middlewares/chart/builder.go]: I tested the chart deletion URL (`"/api/chartrepo/:repo/charts/:name/:version"`) in harbor, the `repo`, `name` and `version` do not match string include `/`.

So `"/api/chartrepo/library/charts/123/123/123/1.0"` will 404 in harbor.

The URL pattern `"/api/:repo/charts/:name/:version"` of `chartmuseum` also do not match string include `/` in `repo`, `name` and `version`.

Comment (wy65701436) [reply src/core/middlewares/chart/builder.go]: but, I can upload the `123/123/123.tgz` with harbor UI.
