### PR TITLE
fix(redis) redis sentinel for chart cache

### LINKED ISSUE #13485: redis+sentinel cannot be used as core chart cache
**Expected behavior and actual behavior:**
**Expected:** redis+sentinel can be used for chart cache.
**Actual:** redis+sentinel cannot be used for chart cache

**Steps to reproduce the problem:**
* Run harbor core with `CHART_CACHE_DRIVER=redis_sentinel`
* Observe harbor core log.
```
2020-11-10T15:03:25Z [ERROR] [/chartserver/controller.go:62]: failed to get cache configuration with error: cache driver 'redis_sentinel' is not supported, only support 'memory' and 'redis'
2020-11-10T15:03:25Z [INFO] [/chartserver/controller.go:66]: No cache is enabled for chart caching
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.1]

**Additional context:**

`redis_sentinel` driver cannot be used because only `redis` or `memory` are allowed:
https://github.com/goharbor/harbor/blob/d32527dfd77a87f8a9913904c0652146e9c32c38/src/chartserver/cache.go#L20-L22
https://github.com/goharbor/harbor/blob/d32527dfd77a87f8a9913904c0652146e9c32c38/src/chartserver/cache.go#L62-L64

### PR DESCRIPTION
**Pull request by bitsf**
close #13485
fix redis sentinel for chartmuseum cache
this only impact the chart detail page

### CODE REVIEW

File: src/chartserver/cache.go [hunk 1]
```diff
@@ -107,6 +107,8 @@ func (chc *ChartCache) PutChart(chart *ChartVersionDetails) {
 		case cacheDriverMem:
 			// Directly put object in
 			err = chc.cache.Put(chart.Metadata.Digest, chart, standardExpireTime)
+		case cacheDriverRedisSentinel:
+			fallthrough
 		case cacheDriverRedis:
```
Comment (heww) [inline src/chartserver/cache.go:112]:
```go
case cacheDriverRedis, cacheDriverRedis:
```

Comment (bitsf) [reply src/chartserver/cache.go]: fixed

**Review by heww — APPROVED** [review]

**Review by steven-zou — APPROVED** [review]
LGTM
