### PR TITLE
[Token/JWT] Update to golang-jwt v5.2.0

### LINKED ISSUE #18880: Failed to push blob to local repo, error: http status code: 401
hi details about the setup, using 2.5.1 version on OpenShift 4.11, 

harbor-core:v2.5.1

So have configured proxy cache projects for upstream registries, when trying to pull images , we intermittently  see the below message and we dont see the repo created in the UI as well, the folders are visible when I check the volume. 

Unsuccessful 
_Failed to push blob to local repo, error: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to access repository:_

successful 
```
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'InternalArtifact' on topic 'PUSH_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator-harbor#proxy-cache-service OccurAt-2023-06-28 09:51:51
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'InternalArtifact' on topic 'PULL_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator- OccurAt-2023-06-28 09:51:51
2023-06-28T09:51:51Z [INFO] [/controller/event/handler/webhook/artifact/artifact.go:75]: []
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'ArtifactWebhook' on topic 'PUSH_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator-harbor#proxy-cache-service OccurAt-2023-06-28 09:51:51
2023-06-28T09:51:51Z [INFO] [/controller/event/handler/webhook/artifact/artifact.go:75]: []
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'ArtifactWebhook' on topic 'PULL_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator- OccurAt-2023-06-28 09:51:51
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'AuditLog' on topic 'PULL_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator- OccurAt-2023-06-28 09:51:51
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'Replication' on topic 'PUSH_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator-harbor#proxy-cache-service OccurAt-2023-06-28 09:51:51
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'AuditLog' on topic 'PUSH_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator-harbor#proxy-cache-service OccurAt-2023-06-28 09:51:51
2023-06-28T09:51:51Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'P2PPreheat' on topic 'PUSH_ARTIFACT': ID-5, Repository-prod.registry.docker.site.gs.com/goharbor/harbor-exporter Tags-[v2.5.1] Digest-sha256:566be56fa88b377d858ec846832cef26542dfea1e5001b7986f9c22f3e6907b1 Operator-harbor#proxy-cache-service OccurAt-2023-06-28 09:51:51
```

### PR DESCRIPTION
**Pull request by an-toine**
# Comprehensive Summary of your change

This PR is a follow-up of #19796 and, if validated, could supplant it.

Both PR share a similar goal, providing some leeway around token validity timestamps to account for clock skew on distributed systems.

This time though, this PR is leveraging the built-in `leeway` attribute brought by the `v5` branch of golang-jwt instead of setting a fix offset on claims.

This code should be carefully reviewed, I'm new to the Harbor codebase and I may have missed some key issues during the migration (I used https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md for this task).

Finally, the leeway value was set arbitrarily, we can maybe use an higher value (up to 1 minute) to improve reliability.

# Issue being fixed
[Fixes #18880](https://github.com/goharbor/harbor/issues/18880)

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [X] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [X] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

cc @Vad1mo

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]

**Comment by MinerYang** [comment]
Hi @an-toine ,

Could you help to resolve  conflict and rebase the branch?

Appreciate!

**Comment by an-toine** [comment]
> Hi @an-toine ,
> 
> Could you help to resolve conflict and rebase the branch as well as update the leeway to 60s as we discussed at your convenience?
> 
> Appreciate!

I've fixed the conflict, rebased, updated leeways and added two test cases to validate change effectiveness.

Antoine

File: src/server/middleware/security/v2_token.go [hunk 1]
```diff
@@ -67,7 +59,8 @@ func (vt *v2Token) Generate(req *http.Request) security.Context {
 		logger.Warningf("failed to decode bearer token: %v", err)
 		return nil
 	}
-	if err := t.Claims.Valid(); err != nil {
+	var v = jwt.NewValidator(jwt.WithLeeway(60 * time.Second), jwt.WithAudience(svc_token.Registry))
```
Comment (MinerYang) [inline src/server/middleware/security/v2_token.go:62]: This line failed with go fmt lint check
Please help to update it with below
```
var v = jwt.NewValidator(jwt.WithLeeway(60*time.Second), jwt.WithAudience(svc_token.Registry))
```

**Review by MinerYang — APPROVED** [review]

File: src/server/middleware/security/v2_token.go (hunk 1 above)
Comment (an-toine) [reply src/server/middleware/security/v2_token.go]: fixed by e22a356, sorry for all these back and forth!

File: src/pkg/token/token.go [hunk 2]
```diff
@@ -65,7 +66,8 @@ func Parse(opt *Options, rawToken string, claims jwt.Claims) (*Token, error) {
 	if err != nil {
 		return nil, err
 	}
-	token, err := jwt.ParseWithClaims(rawToken, claims, func(token *jwt.Token) (interface{}, error) {
+	var parser = jwt.NewParser(jwt.WithLeeway(time.Duration(60) * time.Second))
+	token, err := parser.ParseWithClaims(rawToken, claims, func(token *jwt.Token) (interface{}, error) {
```
Comment (MinerYang) [inline src/pkg/token/token.go:70]: Hi @an-toine ,

seems like we could use jwt.ParseWithClaims(...) here per https://github.com/golang-jwt/jwt/blob/b27c88965d976075194dc8125f1f9c60bd8cf162/parser.go#L55

File: src/pkg/token/claims/v2/claims.go [hunk 3]
```diff
@@ -39,7 +40,9 @@ type Claims struct {
 
 // Valid checks if the issuer is harbor
 func (c *Claims) Valid() error {
-	if err := c.RegisteredClaims.Valid(); err != nil {
+	var v = jwt.NewValidator(jwt.WithLeeway(60 * time.Second))
+
+	if err := v.Validate(c.RegisteredClaims); err != nil {
 		return err
 	}
 	if subtle.ConstantTimeCompare([]byte(c.Issuer), []byte(Issuer)) == 0 {
```
Comment (MinerYang) [inline src/pkg/token/claims/v2/claims.go:48]: we could probably remove this `subtle.ConstantTimeCompare` part with  `jwt.NewValidator(jwt.WithIssuer(c.Issuer))`. As it all aims to compare the issuer.

Comment (an-toine) [reply src/pkg/token/claims/v2/claims.go]: Should be addressed by 899634c

File: src/pkg/token/token.go (hunk 2 above)
Comment (an-toine) [reply src/pkg/token/token.go:70]: Should be addressed by 899634c

**Comment by an-toine** [comment]
@MinerYang : can you retest please ?

**Comment by MinerYang** [comment]
> @MinerYang : can you retest please ?

Hi @an-toine ,

Thanks and sorry for the late response since I was just came back from holiday.

File: src/pkg/token/token.go (hunk 2 above)
Comment (MinerYang) [reply src/pkg/token/token.go:70]: Seems like there's a shortcut  for NewParser().ParseWithClaims() that we could use directly as `jwt.ParseWithClaims()` with parse options
https://github.com/golang-jwt/jwt/blob/b27c88965d976075194dc8125f1f9c60bd8cf162/parser.go#L236C6-L236C21
Anyway, to claim a new parser with options separately may be more readable.

File: src/pkg/token/token.go [hunk 4]
```diff
@@ -34,8 +35,8 @@ type Token struct {
 
 // New ...
 func New(opt *Options, claims jwt.Claims) (*Token, error) {
-	err := claims.Valid()
-	if err != nil {
+	var v = jwt.NewValidator(jwt.WithLeeway(60 * time.Second))
```
Comment (MinerYang) [inline src/pkg/token/token.go:38]: Since we align with upstream distribution/distribution token convention, would it better to use it leeway as `jwt.WithLeeway(token.Leeway)`  in case of we need track the upstream changes manually in the future.

File: src/pkg/token/token_test.go [hunk 5]
```diff
@@ -92,6 +92,42 @@ func TestRaw(t *testing.T) {
 	assert.NotNil(t, rawTk)
 }
 
+func TestRawWithClockSkew(t *testing.T) {
```
Comment (MinerYang) [inline src/pkg/token/token_test.go:95]: IMO, it might be make more sense to write the `TestNewWithClockSkew` instead of `TestRawWithClockSkew` since the we do validation directly on the `New()`

**Review by wy65701436 — APPROVED** [review]
lgtm

File: src/pkg/token/token_test.go (hunk 5 above)
Comment (an-toine) [reply src/pkg/token/token_test.go]: Fixed by a788b68

File: src/pkg/token/token.go (hunk 4 above)
Comment (an-toine) [reply src/pkg/token/token.go]: Fixed by a788b68

**Comment by MinerYang** [comment]
Thanks @an-toine for your dedicated contribution!

Best,
Miner
