### PR TITLE
Fix filter will always show loading when call API failed

### LINKED ISSUE #7701: New replication rule dialog will always show loading when call API failed
What can we help you?
WX20190507-174139@2x

### PR DESCRIPTION
**Pull request by pureshine**
fix #7701 
New replication rule dialog will always show filter loading when call API failed，
Add error handling, loading disappears and displays error message when call API failed

image

Signed-off-by: FangyuanCheng <fangyuanc@vmware.com>

### CODE REVIEW

File: src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts [hunk 1]
```diff
@@ -361,28 +366,34 @@ export class CreateEditRuleComponent implements OnInit, OnDestroy {
...
     if (ruleId) {
+      this.onGoing = true;
       this.policyId = +ruleId;
       this.headerTitle = "REPLICATION.EDIT_POLICY_TITLE";
       this.repService.getReplicationRule(ruleId)
         .subscribe((ruleInfo) => {
           let srcRegistryId = ruleInfo.src_registry.id;
           this.repService.getRegistryInfo(srcRegistryId)
             .subscribe(adapter => {
+              this.onGoing = false;
```
Comment (jwangyangls) [inline src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts]: with line 381,why not use finalize like line391?
