### PR TITLE
Username from /userinfo

### LINKED ISSUE #14037: OIDC Onboarding fails, if username is not present in the ID Token
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Harbor is creating an ID Token without extra claims, but expecting the username to be part of the ID Token. This is true for some OIDCs, but not defined in the standard.
Harbor fails early and is not able to receive the username from the /userinfo endpoint, as expected.

**Steps to reproduce the problem:**

I tried to use [Satosa](https://github.com/IdentityPython/SATOSA) and this occurred.

OIDC config:
* OIDC Scope: openid,name,groups,profile
* Automatic onboarding: true
* Username Claim: "username"

**Versions:**
- harbor version: [2.1.3] and [master]
- docker engine version: [20.10.2]
- docker-compose version: [1.27.4]

### PR DESCRIPTION
**Pull request by shaardie**
This patch enabled Harbor to receive the username from the /userinfo endpoint
instead of only from the ID Token.

Closes #14037

### CODE REVIEW

**Comment by reasonerjt** [comment]
I don't think this is consistent with the design, currently, the "username Claim" in OIDC setting is for automatic onboarding a user.

In your change, if the  "username Claim" is set by mistake the username will be fetched via the `/userinfo` endpoint.

**Review by reasonerjt — APPROVED** [review]

**Review by wy65701436 — APPROVED** [review]
Lgtm

File: src/common/utils/oidc/helper.go [hunk 1]
```diff
@@ -264,6 +264,10 @@ func UserInfoFromToken(ctx context.Context, token *Token) (*UserInfo, error) {
 	if err != nil {
 		log.Warningf("Failed to get userInfo by calling remote userinfo endpoint, error: %v ", err)
 	}
+
+	if setting.UserClaim != "" && local.Username == "" && remote.Username == "" {
```
Comment (reasonerjt) [inline src/common/utils/oidc/helper.go:268]: nil pointer?
