### PR TITLE
fix: fix the invalid jobid for scan data export

### LINKED ISSUE #18380: CVE export error "404 page not found"
Hi all,

In our environment (Harbor `v2.7.0`) we detected the issue with exporting the CVE report.

image

`jobservice.log:`
```
Mar 20, 2023 @ 19:46:19.396    Mar 20 15:16:19 172.20.0.1 jobservice[25867]: 2023-03-20T14:16:19Z [ERROR] [/jobservice/job/impl/scandataexport/scan_data_export.go:130]: Export Job Id = 7.678138e+06. Error when persisting report file /var/scandata_exports/scandata_export_7.678138e+06.csv to persistent storage: http status code: 404, body: 404 page not found    
Mar 20, 2023 @ 19:45:48.329    Mar 20 15:15:48 172.20.0.1 jobservice[25867]: 2023-03-20T14:15:48Z [ERROR] [/jobservice/job/impl/scandataexport/scan_data_export.go:130]: Export Job Id = 7.678137e+06. Error when persisting report file /var/scandata_exports/scandata_export_7.678137e+06.csv to persistent storage: http status code: 404, body: 404 page not found    
Mar 20, 2023 @ 19:45:25.889    Mar 20 15:15:25 172.20.0.1 jobservice[25867]: 2023-03-20T14:15:25Z [ERROR] [/jobservice/job/impl/scandataexport/scan_data_export.go:130]: Export Job Id = 7.678135e+06. Error when persisting report file /var/scandata_exports/scandata_export_7.678135e+06.csv to persistent storage: http status code: 404, body: 404 page not found
```

We already checked the permissions in the filesystem and the Docker configuration and we didn't saw any "strange" configuration.

Does anyone have an idea, why this is not working?

P.S.: Maybe related to https://github.com/goharbor/harbor-helm/issues/1444

Thank you in advance!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

### PR DESCRIPTION
**Pull request by chlins**
Change the JobId param type from int to string, use int will bring some problems for encode/decode type mismatch which generate the invalid repository name.

Fixes: #18380

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #18380

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

File: src/jobservice/job/impl/scandataexport/scan_data_export.go [hunk 1]
```diff
@@ -177,7 +183,7 @@ func (sde *ScanDataExport) writeCsvFile(ctx job.Context, params job.Parameters,
 	var exportParams export.Params
 	var artIDGroups [][]int64
 
-	if criteira, ok := params["Request"]; ok {
+	if criteira, ok := params[export.JobRequest]; ok {
```
Comment (zyyw) [inline src/jobservice/job/impl/scandataexport/scan_data_export.go:186]: typo: `criteira` should be `criteria`

**Review by zyyw — APPROVED** [review]
approved with one comment

**Review by wy65701436 — APPROVED** [review]
lgtm
