### PR TITLE
Skip admin and change oidc user not found message more readable

### LINKED ISSUE #21041: Admin, error: failed to get oidc user info, error: <QuerySeter> no row found
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Getting frequent error on the harbor core container 

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
Enable OIDC authentication
enable OIDC user login except admin user

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.11.1

Error Logs:
`2024-09-19T16:56:12Z [ERROR] [/server/middleware/security/oidc_cli.go:68][requestID="242bf2db33e997bf2c69f93d81f51db8"]: failed to verify secret, username: admin, error: failed to get oidc user info, error: <QuerySeter> no row found
2024-09-19T16:56:42Z [ERROR] [/server/middleware/security/oidc_cli.go:68][requestID="fa0b94915681af7a535e11c2af207b0e"]: failed to verify secret, username: admin, error: failed to get oidc user info, error: <QuerySeter> no row found
2024-09-19T16:57:12Z [ERROR] [/server/middleware/security/oidc_cli.go:68][requestID="195ee11d4bd8ea0c39368145cf76c153"]: failed to verify secret, username: admin, error: failed to get oidc user info, error: <QuerySeter> no row found
2024-09-19T16:57:42Z [ERROR] [/server/middleware/security/oidc_cli.go:68][requestID="4539600fe12d22a94fd11623237bded8"]: failed to verify secret, username: admin, error: failed to get oidc user info, error: <QuerySeter> no row found`

### PR DESCRIPTION
**Pull request by stonezdj**
fixes #21041
  verified in local env
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
+1

**Comment by peters-david** [comment]
+1

File: src/server/middleware/security/oidc_cli.go [hunk 1]
```diff
@@ -65,6 +65,11 @@ func (o *oidcCli) Generate(req *http.Request) security.Context {
 
 	info, err := oidc.VerifySecret(ctx, username, secret)
 	if err != nil {
+		user, err2 := uctl.GetByName(ctx, username)
+		// skip to log the error if the user is the admin user
+		if err2 == nil && user != nil && user.UserID == 1 {
+			return nil
```
Comment (Vad1mo) [inline src/server/middleware/security/oidc_cli.go:71]: Log at debug level for admin users as this might be expected

logger.Debugf("OIDC verification failed for admin user %s: %v", username, err)

File: src/pkg/oidc/secret.go [hunk 2]
```diff
@@ -86,6 +87,9 @@ var m SecretManager = &defaultManager{
 func (dm *defaultManager) VerifySecret(ctx context.Context, username string, secret string) (*UserInfo, error) {
 	log.Debugf("Verifying the secret for user: %s", username)
 	oidcUser, err := dm.metaDao.GetByUsername(ctx, username)
+	if strings.Contains(err.Error(), "no row found") {
```
Comment (Vad1mo) [inline src/pkg/oidc/secret.go:90]: Checking error strings is fragile. Would not be better to:
1.  Use proper error types or sentinel errors
2. Check if the error implements a specific interface

**Review by Vad1mo — CHANGES_REQUESTED** [review]

File: src/pkg/oidc/secret.go (hunk 2 above)
Comment (stonezdj) [reply src/pkg/oidc/secret.go:90]: Updated

File: src/server/middleware/security/oidc_cli.go (hunk 1 above)
Comment (stonezdj) [reply src/server/middleware/security/oidc_cli.go:71]: No need to dump information for admin user.

File: src/server/middleware/security/oidc_cli.go [hunk 3]
```diff
@@ -65,6 +65,11 @@ func (o *oidcCli) Generate(req *http.Request) security.Context {
 
 	info, err := oidc.VerifySecret(ctx, username, secret)
 	if err != nil {
+		user, err2 := uctl.GetByName(ctx, username)
```
Comment (wy65701436) [inline src/server/middleware/security/oidc_cli.go:68]: We should avoid calling the uctl.GetByName twice, I suggest rewriting it as following:

```
        u, err := uctl.GetByName(ctx, username)
	if err != nil {
		logger.Errorf("failed to get user model, username: %s, error: %v", username, err)
		return nil
	}

	info, err := oidc.VerifySecret(ctx, username, secret)
	if err != nil {
		if u.UserID == 1 {
			return nil
		}
		logger.Errorf("failed to verify secret, username: %s, error: %v", username, err)
		return nil
	}
```

File: src/pkg/oidc/secret.go [hunk 4]
```diff
@@ -86,6 +88,9 @@ var m SecretManager = &defaultManager{
 func (dm *defaultManager) VerifySecret(ctx context.Context, username string, secret string) (*UserInfo, error) {
 	log.Debugf("Verifying the secret for user: %s", username)
 	oidcUser, err := dm.metaDao.GetByUsername(ctx, username)
+	if errors.Is(err, orm.ErrNoRows) {
```
Comment (wy65701436) [inline src/pkg/oidc/secret.go:91]: Can we move the check into the DAO? This would allow other callers to avoid duplicating the same logic.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by chlins — APPROVED** [review]
lgtm
