### PR TITLE
fix conformance failure

### LINKED ISSUE #15252: Conformance test failure on heand & get non-exist manifest
```
2021/07/01 06:25:25.755352 DEBUG 
==============================================================================
~~~ REQUEST ~~~
GET  /v2/conformance/testrepo/manifests/.INVALID_MANIFEST_NAME  HTTP/1.1
HOST   : 10.1.1.98
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 401 Unauthorized
RECEIVED AT  : 2021-07-01T06:25:25.755103178Z
TIME DURATION: 2.448743ms
HEADERS      :
	Connection: keep-alive
	Content-Length: 220
	Content-Type: application/json; charset=utf-8
	Date: Thu, 01 Jul 2021 06:25:25 GMT
	Docker-Distribution-Api-Version: registry/2.0
	Server: nginx
	Set-Cookie: sid=5f2e49163fa58307b2fd14ca0ea12127; Path=/; HttpOnly; Secure
	Www-Authenticate:
	X-Request-Id: ab3f33cb-3423-4390-8a10-0e24dcf8948f
BODY         :
{
   "errors": [
      {
         "code": "UNAUTHORIZED",
         "message": "un-recognized request: GET /v2/conformance/testrepo/manifests/.INVALID_MANIFEST_NAME: un-recognized request: GET /v2/conformance/testrepo/manifests/.INVALID_MANIFEST_NAME"
      }
   ]
}

==============================================================================
```

### PR DESCRIPTION
**Pull request by wy65701436**
fixes #15252

Give 404 for invalid digest when to get/head manifest

Signed-off-by: Wang Yan <wangyan@vmware.com>

### CODE REVIEW

File: src/server/middleware/artifactinfo/artifact_info_test.go [hunk 1]
```diff
@@ -60,8 +60,12 @@ func TestParseURL(t *testing.T) {
 		{
 			input: "/v2/development/golang/manifests/shaxxx:**********************************************************************************************************************************",
 
-			expect: map[string]string{},
-			match:  false,
+			expect: map[string]string{
+				lib.RepositorySubexp: "development/golang",
+				lib.ReferenceSubexp:  "shaxxx:**********************************************************************************************************************************",
+				"tag":                "shaxxx:**********************************************************************************************************************************",
```
Comment (reasonerjt) [inline src/server/middleware/artifactinfo/artifact_info_test.go:66]: In this case the tag should be empty.

We should fail early for 400 or 404 at the middleware level.  Otherwise the artifact Info data will be different in the subsequent codepath.

**Review by reasonerjt — APPROVED** [review]

**Comment by reasonerjt** [comment]
Could you add the `.Invalid` reference into `src/server/middleware/artifactinfo/artifact_info_test.go` as a test case to clarify what the artifactInfo should look like when the reference is invalid?

**Review by heww — APPROVED** [review]
