### PR TITLE
fix bug found in the pluggable scanner

### LINKED ISSUE #9632: Http code is changed from 200 to 202 for scan request submitting, scan all is still using 200
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

No errors logged but now many error logs appeared in the log file

**Steps to reproduce the problem:**

Just trigger a scan action

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

> Oct 29 00:00:00 192.168.176.1 jobservice[1185]: 2019-10-29T00:00:00Z [ERROR] [/jobservice/runner/redis.go:191]: Unexpected response code: 202, data: []
Oct 29 00:00:01 192.168.176.1 jobservice[1185]: 2019-10-29T00:00:01Z [ERROR] [/jobservice/runner/redis.go:191]: Unexpected response code: 202, data: []
Oct 29 00:00:01 192.168.176.1 jobservice[1185]: 2019-10-29T00:00:01Z [ERROR] [/jobservice/runner/redis.go:191]: Unexpected response code: 202, data: []
Oct 29 01:50:41 192.168.176.1 jobservice[1185]: 2019-10-29T01:50:41Z [ERROR] [/jobservice/runner/redis.go:191]: Unexpected response code: 202, data: []
Oct 29 01:50:41 192.168.176.1 jobservice[1185]: 2019-10-29T01:50:41Z [ERROR] [/jobservice/runner/redis.go:191]: Unexpected response code: 202, data: []
Oct 29 01:50:41 192.168.176.1 jobservice[1185]: 2019-10-29T01:50:41Z [ERROR] [/jobservice/runner/redis.go:191]: Unexpected response code: 202, data: []

### LINKED ISSUE #9633: A nil error log printed when initializing the the scan event subscription
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

No error log should be printed but now a nil error is also printed

>Oct 28 15:40:02 192.168.176.1 core[1185]: 2019-10-28T15:40:02Z [ERROR] [/pkg/scan/event/init.go:29]: <nil>

**Steps to reproduce the problem:**
With a fresh Harbor installation.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

<NONE>

### PR DESCRIPTION
**Pull request by steven-zou**
- fix #9632
- fix #9633

Signed-off-by: Steven Zou <szou@vmware.com>

### CODE REVIEW

File: src/jobservice/job/impl/scan/all.go [hunk 1]
```diff
@@ -95,7 +95,7 @@ func (sa *All) Run(ctx job.Context, params job.Parameters) error {
 				data, err := ioutil.ReadAll(resp.Body)
 				if err != nil {
 					logger.Errorf("Failed to read response, error: %v", err)
-				} else if resp.StatusCode != http.StatusOK {
+				} else if resp.StatusCode/100 != 2 {
```
Comment (heww) [inline src/jobservice/job/impl/scan/all.go]: According to the `Scanner Adapter API` in the proposal,  the status code is `StatusAccepted`( 202 ) when submit scan request success and the `/api/repositories/*/tags/:tag/scan` also return `StatusAccepted` when success.

Comment (steven-zou) [reply src/jobservice/job/impl/scan/all.go]: I know that, to avoid changing again. So, I use a general way.

Comment (steven-zou) [reply src/jobservice/job/impl/scan/all.go]: let's use 202 replace it
