### PR TITLE
Store Username in auto-onboard flow (resolves #16180)

### LINKED ISSUE #16180: OIDC - Unable to recover username for auto onboard
With auto-onboard enabled, user login through OIDC fails with error in harbor-core: 
```
{"code":"INTERNAL_SERVER_ERROR","message":"unable to recover username for auto onboard, username claim: email"}
```
However, the username claim `email` **is** included in the user info string:
```
[DEBUG] [/core/controllers/oidc.go:225]: User info string: {"iss":"https://login.hooli.com/adfs","sub":"YzI5dFpWUm9hVzVuVW1GdVJHOXRSazlTWjJsVVNWTlRkV1U9=","name":"","email":"gilfoyle.bertram@hooli.com","groups":["Pied_Piper_Admin"],"admin_group_member":true}
```

We have multiple Harbor instances, one for prod (v2.2.1-b0d63082) and one for test (v2.4.1-c4b06d79). Test has a newer version and is not working. Prod works fine with equal settings. We're hesitating to update prod as this issue would have a very high impact.

We're using an OIDC logging provider with the following settings:*

| Auth Mode            | OIDC                                       |
|----------------------|--------------------------------------------|
| OIDC Provider Name   | HOOLI-CORP                                 |
| OIDC Endpoint        | https://login.hooli.com/adfs               |
| OIDC Client ID       | REDACTED                                   |
| OIDC Client Secret   | REDACTED                                   |
| Group Claim Name     | group                                      |
| OIDC Admin Group     | Pied_Piper_Admin                           |
| OIDC Scope           | email,offline_access,openid,profile,groups |
| Verify Certificate   | TRUE                                       |
| Automatic onboarding | TRUE                                       |
| Username Claim       | email                                      |  

\* _Sensitive info has been redacted_

## Expected behaviour
OIDC login should succeed with auto-onboard enabled, as the user info string contains the email of the logged in user. Instead the user instantly gets the following error after successfully logging in at our OIDC provider and thus is unable to access Harbor:
```
{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
```
This seems to correspond with error log below in harbor-core:
```
[DEBUG] [/pkg/oidc/helper.go:209]: Raw ID token for verification: REDACTED
[WARNING] [/pkg/oidc/helper.go:271]: Failed to get userInfo by calling remote userinfo endpoint, error: 401 Unauthorized:  
[DEBUG] [/pkg/oidc/helper.go:281]: Fall back to user data from ID token.
[DEBUG] [/core/controllers/oidc.go:132]: Doing automatic onboarding
[ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"unable to recover username for auto onboard, username claim: email"}]} 
```
I checked the Raw JWT token by decoding it back to JSON, which results in:
```json
{
  "aud": "REDACTED",
  "iss": "https://login.hooli.com/adfs",
  "iat": 1640792352,
  "exp": 1640795952,
  "auth_time": 1640792238,
  "mfa_auth_time": 1640792250,
  "sub": "REDACTED",
  "upn": "gilfoyle.bertram@hooli.com",
  "unique_name": "HOOLI\\gilfoyle001",
  "pwd_exp": "4902352",
  "sid": "REDACTED",
  "email": "gilfoyle.bertram@hooli.com",
  "group": [
    "Pied_Piper_Admin"
  ],
  "apptype": "Confidential",
  "appid": "REDACTED",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "ver": "1.0",
  "scp": "profile openid offline_access email"
}
```
To me this looks to be complete, as it contains both the neccessary username claim (email) and list of group(s). 

## Steps to reproduce
1. Enable login through OIDC and ADFS provider
1. Enable auto-onboard
1. Try to login as OIDC-user  

## Workaround
When disabling auto-onboard, OIDC login does work and the User info string seem to contain the necessary info. 
```
[DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="c29tZVRoaW5nUmFuRG9tRk9SZ2lUSVNTdWU="]: an unauthorized security context generated for request POST /c/oidc/onboard
[DEBUG] [/core/controllers/oidc.go:225]: User info string: {"iss":"https://login.hooli.com/adfs","sub":"YzI5dFpWUm9hVzVuVW1GdVJHOXRSazlTWjJsVVNWTlRkV1U9=","name":"","email":"gilfoyle.bertram@hooli.com","groups":["Pied_Piper_Admin"],"admin_group_member":true}
[DEBUG] [/core/controllers/oidc.go:193]: User created: gilfoyle.bertram@hooli.com
```

## Versions
Our instance is installed using the latest Helm Chart (2.4.1) onto our Kubernetes cluster:
* Harbor: 2.4.1
* Docker engine: 19.3.12
* Helm Version: 3.7.2

## Additional context:
I think information above shoul be sufficient to diagnose the issue, but if not; please let me know and I'll provide everything that's neccessary.

### PR DESCRIPTION
**Pull request by JoooostB**
This PR resolves #16180, which seems to come down to the username not being set properly whenever `userInfoFromRemote` fails in `UserInfoFromToken`:
https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L269

When above fails, [mergeUserInfo](https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L287) is never called, which leads to `local.Username` to remain empty (as this is handled by `mergeUserInfo`).
https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L273-L277
What I'd like to suggest is setting the Username if it's still empty, after setting the autoOnboardUsername, as it was prior to #15625 :
https://github.com/goharbor/harbor/blob/03b7b01f77faab31d9205f1dfbb129b2272242ea/src/pkg/oidc/helper.go#L350-L351

The change has been tested and resolved our issue entirely.

### CODE REVIEW

**Comment by JoooostB** [comment]
Force push due to DCO

**Comment by JoooostB** [comment]
Any chance you can take a look at this PR @reasonerjt?

File: src/pkg/oidc/helper.go [hunk 1]
```diff
@@ -356,6 +356,11 @@ func userInfoFromClaims(c claimsProvider, setting cfgModels.OIDCSetting) (*UserI
 
 		if username, ok := allClaims[setting.UserClaim].(string); ok {
 			res.autoOnboardUsername = username
+			// If User is not onboarded yet, store Username as well
+			// Otherwise, onboard flow would fail if "name" is not set in token
+			if res.Username == "" {
```
Comment (reasonerjt) [inline src/pkg/oidc/helper.go:361]: This `if` may not be needed, b/c at this point the Username may be set if the token has `name` attribute, but the expected result is that the Username is always set as the autoOnboard setting.

Could you please also add a comment to explicitly explain that the func `mergeUserInfo` may not be called, so the `res.Username` must be set in this case.

Comment (JoooostB) [reply src/pkg/oidc/helper.go]: I've removed the conditional and added some extra comments regarding the purpose of this change.

**Comment by JoooostB** [comment]
Force push due to DCO

**Comment by reasonerjt** [comment]
@JoooostB 
This case should be updated according to the change you make:
https://github.com/goharbor/harbor/blob/main/src/pkg/oidc/helper_test.go#L271-L293

**Comment by JoooostB** [comment]
Squashed commits.

**Review by reasonerjt — APPROVED** [review]
lgtm

**Review by wy65701436 — APPROVED** [review]
lgtm
