### PR TITLE
fix GC jobs upgrade issue

### LINKED ISSUE #11275: There should be logs in GC for removal of untagged artifacts
Since we introduce the remove untagged artifacts flag in GC.

When there are untagged artifacts removed,  there should be explicit log messages in the GC job log.

### LINKED ISSUE #11313: GC schedule job failed after upgrade from 1.10 to 2.0
build 3166

image
image

### PR DESCRIPTION
**Pull request by wy65701436**
Fixes #11313
Fixes #11275

1, Add more details log in GC job
2, Add type assertion for the upgrading case, the delete_untagged parameter is introduced from v2.0

Signed-off-by: wang yan <wangyan@vmware.com>

### CODE REVIEW

File: src/jobservice/job/impl/gc/garbage_collection.go [hunk 1]
```diff
@@ -139,29 +158,21 @@ func (gc *GarbageCollector) init(ctx job.Context, params job.Parameters) error {
 	gc.redisURL = params["redis_url_reg"].(string)
 
 	// default is to delete the untagged artifact
-	if params["delete_untagged"] == "" {
+	deleteUntagged, exist := params["delete_untagged"]
```
Comment (steven-zou) [inline src/jobservice/job/impl/gc/garbage_collection.go:161]: I think you just need a convention `ok` flag

```go
deleteUntagged, exist := params["delete_untagged"]
if exist {
   if untagged, ok := deleteUntagged.(bool); ok && untagged {
      // do untagged things
  }
}
```

Comment (wy65701436) [reply src/jobservice/job/impl/gc/garbage_collection.go:162]: updated
