### PR TITLE
[fix] Fix  issue in front ui 2.0.1

### LINKED ISSUE #9863: UI should redirect to login page
When session timeout, click on some page, it will fail with 401, and show a login button, and page can still be see and navigate.
It is better to redirect to login page directly.

image

### LINKED ISSUE #12092: add label failed
Harbor 2.0.0
When adding labels to artifacts, select the first can success, then select the second one will fail. Refresh UI can fix.
image

This should be something wrong with UI refresh.

### PR DESCRIPTION
**Pull request by jwangyangls**
https://10.78.96.167
fix #12092； fix #9863
Signed-off-by: Yogi_Wang <yawang@vmware.com>

### CODE REVIEW

File: src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts [hunk 1]
```diff
@@ -446,11 +446,11 @@ export class ArtifactListTabComponent implements OnInit, OnDestroy {
...
+    this.imageStickLabels.forEach(data => {
+      data.iconsShow = false;
+      data.show = true;
+    });
     if (artifact && artifact[0].labels) {
-      this.imageStickLabels.forEach(data => {
-        data.iconsShow = false;
-        data.show = true;
-      });
       if (artifact[0].labels.length) {
```
Comment (selina-cui) [inline src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts:454]: Cloud you combine this condition with previous line?
