### PR TITLE
(cherry-pick) Add content type and length in header

### LINKED ISSUE #13740: docker 20.10 pull proxy cache image failed: Error response from daemon: missing or empty Content-Type header
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

should pull proxy cache repo images success.

but docker 20.10 pull proxy cache repo images got  error `missing or empty Content-Type header`

**Steps to reproduce the problem:**
 
```bash
# docker.io is a proxy cache project
docker pull ${HARBOR_HOST}/docker.io/library/alpine:3.12
Error response from daemon: missing or empty Content-Type header
```
logs of docker desktop for mac

image

works well with docker 19.03.x
normal project works well

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.1-5f52168e
- docker engine version: 20.10

### PR DESCRIPTION
**Pull request by stonezdj**
Fixes #13740
Update ManifestExist to return Descriptor instead of digest
For docker 20.10 or containerd, it HEAD the manifest before pull, then
it GET the manifest with digest, add logic to handle this scenario and
correlate the tag between the digest in proxy cache

Signed-off-by: stonezdj <stonezdj@gmail.com>

### CODE REVIEW

File: src/server/middleware/repoproxy/proxy.go [hunk 1]
```diff
@@ -206,14 +217,31 @@ func DisableBlobAndManifestUploadMiddleware() func(http.Handler) http.Handler {
...
+		for i := 0; i < ensureTagMaxRetry; i++ {
+			time.Sleep(ensureTagInterval)
+			bArt := lib.ArtifactInfo{ProjectName: art.ProjectName, Repository: art.Repository, Digest: string(desc.Digest)}
+			err := ctl.EnsureTag(bCtx, bArt, art.Tag)
+			if err == nil {
+				return
+			}
+			log.Debugf("Failed to ensure tag %+v , error %v", art, err)
+		}
+	}()
```
Comment (reasonerjt) [inline src/server/middleware/repoproxy/proxy.go:241]: pass art as a parm to this func.

**Review by reasonerjt — APPROVED** [review]

File: src/server/middleware/repoproxy/proxy.go (hunk 1 above)
Comment (stonezdj) [reply src/server/middleware/repoproxy/proxy.go]: updated

**Review by ywk253100 — APPROVED** [review]
